### PR TITLE
PowerShell v5 language features

### PR DESCRIPTION
**Pull request by dragon788**
Manually merged in commits from @heaths (see
https://github.com/heaths/vim-ps1/commit/6e1aa82161ae2154ec14a747feb551a6a011918f)
along with some additional changes.

### CODE REVIEW

**Comment by heaths** [comment]
Why couldn't you just add commits to mine rather than taking them over? Besides, mine have been waiting on @pprovost integrating them.

**Comment by dragon788** [comment]
I did not intend to take them over, I was trying to get an updated version to use with all of the fixes and didn't realize that you had already fixed the merge conflicts. Unless the project becomes abandoned I certainly hope mine doesn't become the definitive fork. My goal is to create a fully updated version and then maintain my own set of additions and patches based on the upstream project.

**Comment by heaths** [comment]
You can resolve the merge conflicts while maintaining preview commits. It's bad form to rewrite the author of commits. Besides, it helps with future merge conflicts if and when @pprovost finally merges my PR. Some others have based their work on my PR as well, so you can see them for an example.

**Comment by dragon788** [comment]
@heaths I definitely agree, I was doing the merges from the web, so it wasn't nearly as clean as if I'd done it from the command line. I'm planning on redoing this properly, because I definitely want you to get the credit for your awesome additions.

**Comment by heaths** [comment]
I've merged my changes into the upstream master branch so you can rebase on that if you like.

**Comment by dragon788** [comment]
@heaths Awesome, will definitely redo my fork based on the updated base, thanks for keeping the project moving!

**Pull request closed without merging**
